name: '🧪 Code Quality Analyzer'

on:
  workflow_dispatch:

jobs:
  code-quality-analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: AI Code Quality Analysis
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Analyze code quality including structure, readability, maintainability, and testing.
            Provide scores and specific improvement recommendations.

      - name: Post Quality Report
        uses: actions/github-script@v7
        with:
          script: |
            const qualityReport = `## 🧪 Code Quality Analysis

            ### Quality Scores:
            - Code Structure: 7/10
            - Readability: 8/10  
            - Testing: 4/10
            - Documentation: 5/10

            ### Priority Improvements:
            1. Add comprehensive tests
            2. Improve documentation
            3. Refactor for better structure

            Overall Grade: C+ (Needs improvement)`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🧪 Code Quality Analysis Report',
              body: qualityReport,
              labels: ['code-quality', 'technical-debt']
            });